# This is an example parameter file.
# All values showed here are default values.
# To change a specific parameter value, please uncomment the corresponding line.

#### Basic parameters ####
workpath=./
# prfx={file basename of "--input_micrograph_list"}
# average_mrc={prfx}_avg.mrc
# output_mrc={prfx}_diag.st
# output_file={prfx}_ctf.txt
j=10

#### Parameters for CTF estimation ####
# box=512
# N_zeros=10
# defocus_min=10000.0
# defocus_max=100000.0
# defocus_step=100.0
# resolution_max=4*{pixel_size}
# resolution_min=30.0
# resolution_adaptive=1
# adaptive_range=1
# it=3

#### Advanced parameters ####
# search_phase_shift=0
# box_conv={box}/20
# N_avg=0
# N_ref={Micrograph with minimum tilt angle}
# box_conv_first=1
# skip_box_conv_coarse=0
# hard_restriction=0
# skip_unified=0
# optimize_with_average=1
# per_tilt_estimation=0
# tight_blocks=0
# astigmatism_angstrom=2000
# dose_weighting=0
# dose_acc_file=<accumulated dose file name>
# convergence_defocus=100.0 
# convergence_astigmatism=1.0
# convergence_angle=0.1
# output_raw=0

#### Parameters for angle estimation ####
# tlt_offset=0.0
# xtilt=0.0
# pre_offset_estimation=0
# dose_file=<dose file name>
# skip_offset_estimation=1
# skip_offset_refinement=1
# skip_offset_estimation_x=1
# skip_offset_refinement_x=1
# skip_axis_refinement=1
# skip_angle_refinement=1
# N_avg_block=2

